import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import { Merriweather } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import 'animate.css';

const titilliumWeb = Titillium_Web({
  subsets: ['latin'],
  weight: ['200', '300', '400', '600', '700', '900'], // Specify the weights you need
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${titilliumWeb.className}`}>{children}</body>
    </html>
  );
}
